# AUTOGENERATED FROM:
#     'app/queries/create_job.edgeql'
#     'app/queries/get_job_by_id.edgeql'
#     'app/queries/get_jobs.edgeql'
#     'app/queries/update_job.edgeql'
# WITH:
#     $ edgedb-py --file


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import enum
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateJobResult(NoPydanticValidation):
    id: uuid.UUID
    created_at: datetime.datetime


@dataclasses.dataclass
class GetJobByIdResult(NoPydanticValidation):
    id: uuid.UUID
    threads: int
    status: Status
    input_urls: list[str] | None
    image_urls: list[str] | None
    created_at: datetime.datetime


class Status(enum.Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ERROR = "error"


@dataclasses.dataclass
class UpdateJobResult(NoPydanticValidation):
    id: uuid.UUID


async def create_job(
    executor: edgedb.AsyncIOExecutor,
    *,
    threads: int,
    status: Status,
    input_urls: list[str],
    image_urls: list[str],
) -> CreateJobResult:
    return await executor.query_single(
        """\
        select (insert Job {
            threads := <int16>$threads,
            status := <StatusType>$status,
            input_urls := <array<str>>$input_urls,
            image_urls := <array<str>>$image_urls
        }) {
            id,
            created_at
        };\
        """,
        threads=threads,
        status=status,
        input_urls=input_urls,
        image_urls=image_urls,
    )


async def get_job_by_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetJobByIdResult | None:
    return await executor.query_single(
        """\
        select Job {id, threads, status, input_urls, image_urls, created_at}
        filter Job.id = <uuid>$id\
        """,
        id=id,
    )


async def get_jobs(
    executor: edgedb.AsyncIOExecutor,
) -> list[CreateJobResult]:
    return await executor.query(
        """\
        select Job {id, created_at};\
        """,
    )


async def update_job(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    status: Status,
    image_urls: list[str],
) -> UpdateJobResult | None:
    return await executor.query_single(
        """\
        update Job
        filter Job.id = <uuid>$id
        set {
            status := <StatusType>$status,
            image_urls := <array<str>>$image_urls
        };\
        """,
        id=id,
        status=status,
        image_urls=image_urls,
    )
