# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  NUM_WORKERS: 1
  LOG_LEVEL: info

tasks:
  run:
    cmds:
      - echo "{{.GREETING}}"
      - uvicorn main:app --host=0.0.0.0 --workers="{{.NUM_WORKERS}}" --log-level="{{.LOG_LEVEL}}"

  format:
    cmds:
      - black .
      - ruff . --fix

  lint:
    cmds:
      - black . --check
      - ruff .
      - mypy .

  print-var:
    cmds:
      - echo "{{.VAR}}"